version: '3.8'

services:
  escape-dungeon-gateway:
    image: ukrgerri4/escape-dungeon-gateway:latest
    container_name: escape-dungeon-gateway
    build:
      context: .
      dockerfile: src/EscapeDungeonGateway/Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      nginx:
      internal:
    volumes:
       # for linux config only 
       #- "/var/run/docker.sock:/var/run/docker.sock"
       - temp-keys:/root/.aspnet/DataProtection-Keys
       - logs:/app/logs

volumes:
  temp-keys:
  logs:

networks:
  nginx:
    external: true
    name: nginx-net
  internal:
    external: true
    name: internal-net
