version: '3.8'

services:
  escapedungeongateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"